# Generated by Django 5.0.6 on 2024-05-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimodal_RAG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Multimodal_RAG.document')),
            ],
        ),
    ]
